### ISSUE TITLE
OrganizationRequestBuilder status issue

### ISSUE THREAD

**Issue by vp2** [KuliginStepan/dadata-client#19]
Коллега, здравствуйте :)

Текущая реализация OrganizationRequestBuilder создает запрос на все типы организаций:
`private Set<OrganizationStatus> statuses = EnumSet.allOf(OrganizationStatus.class);`

Как следствие, метод бесполезен:
```
    public OrganizationRequestBuilder status(OrganizationStatus status) {
        statuses.add(status);
        return this;
    }
```

Я для себя решил добавлением метода в свою кастомную реализацию билдера:
```
    public PatchedOrganizationRequestBuilder clearStatuses() {
        statuses.clear();
        return this;
    }
```

Не проверял, но вполне возможно эта же проблема может присутствовать и в других Request Builder'ах.

**Comment by KuliginStepan** [comment]
Добрый день! Спасибо за замечание, действительно проблема присутствовала в нескольких билдерах. Будет исправлено в версии 2.3.1
