### ISSUE TITLE
Проблема с com.kuliginstepan.dadata.client.domain.organization.Organization["capital"]

### ISSUE THREAD

**Issue by jonnydrax** [KuliginStepan/dadata-client#21]
API дадаты отдает в поле капитала объект, а не Double при поиске по инн
Вот пример:
{
  "suggestions": [
    {
      "value": "ООО \"СТЕКЛОКОН\"",
      "unrestricted_value": "ООО \"СТЕКЛОКОН\"",
      "data": {
        "kpp": "772501001",
        "capital": {
          "type": "УСТАВНЫЙ КАПИТАЛ",
          "value": 300010
        },

**Comment by KuliginStepan** [comment]
Исправлено в версии `2.4.0`

**Comment by jonnydrax** [comment]
Спасибо!
