### ISSUE TITLE
Отсутствует поле country_iso_code в классе Address

### ISSUE THREAD

**Issue by vdsirotkin** [KuliginStepan/dadata-client#3]
В классе `com.kuliginstepan.dadata.client.domain.address.Address` отсутствует поле country_iso_code

**Comment by KuliginStepan** [comment]
@vdsirotkin Спасибо за задачу, эти поля были добавлены в API подсказок недавно, планирую их добавить

**Comment by vdsirotkin** [comment]
Я хотел кинуть пулл-реквест на это поле, но не хватило прав, так что пока что я локально пропатчил. Буду ждать обновления!)

**Comment by KuliginStepan** [comment]
@vdsirotkin задача была решена, в релиз попадет после закрытия других активных задач.

**Comment by KuliginStepan** [comment]
@vdsirotkin Репозиторий должен быть открыт для пулл реквестов, нужно сначала сделать форк этого реепозитория, а потом отправить пулл реквест
